export const oilData = [
  {
    id: 1,
    title: "زيت زيتون",
    Image: "../../public/oilImages/زيت الزيتون.jpg",
    price: "225ج.م-240ج.م",
  },
  {
    id: 2,
    title: "زيت بزر الكتان",
    Image: "../../public/oilImages/زيت بذرة الكتان.jpg",
    price: "125ج.م",
  },
  {
    id: 3,
    title: "زيت اللوز الحلو",
    Image: "../../public/oilImages/زيت اللوز الحلوjpg.jpg",
    price: "250ج.م",
  },
  {
    id: 4,
    title: "زيت حبة البركه",
    Image: "../../public/oilImages/زيت حبة البركهjpg.jpg",
    price: "200ج.م",
  },
  {
    id: 5,
    title: "زيت بزر العنب",
    Image: "../../public/oilImages/زيت بذر العنب.jpg",
    price: "250ج.م",
  },
  {
    id: 6,
    title: "زيت حبة البركه",
    Image: "../../public/oilImages/زيت حبة البركه2.jpg",
    price: "200ج.م",
  },
  {
    id: 7,
    title: "زيت جوز الهند",
    Image: "../../public/oilImages/زيت جوز الهند.jpg",
    price: "150ج.م",
  },
  {
    id: 8,
    title: "زيت جوز الهند",
    Image: "../../public/oilImages/زيت جوز الهند2.jpg",
    price: "150ج.م",
  },
  {
    id: 9,
    title: "زيت حبة البركه",
    Image: "../../public/oilImages/زيت حبة البركه 3.jpg",
    price: "200ج.م",
  },
  {
    id: 10,
    title: "زيت جوز الهند",
    Image: "../../public/oilImages/زيت جوز الهند3.jpg",
    price: "150ج.م",
  },
  {
    id: 11,
    title: "زيت حبة البركه",
    Image: "../../public/oilImages/زيت حبة البركه 3.jpg",
    price: "200ج.م",
  },
];

export const honeyData = [
  {
    id: 1,
    title: "عسل صدر مصري",
    Image: "../../public/honey images/عسل صدر جبلي.jpg",
    price: "160ج.م",
  },
  {
    id: 3,
    title: "عسل حبة البركه 1000جم",
    Image: "../../public/honey images/عسل حبة البركه.jpg",
    price: "180ج.م",
  },
  {
    id: 4,
    title: "عسل بردقوش",
    Image: "../../public/honey images/عسل بردقوش.jpg",
    price: "185ج.م",
  },
  {
    id: 5,
    title: "عسل المورينجا",
    Image: "../../public/honey images/عسل المورينجا.jpg",
    price: "73ج.م",
  },
  {
    id: 6,
    title: "عسل بردقوش",
    Image: "../../public/honey images/عسل بردقوش.jpg",
    price: "185ج.م",
  },
  {
    id: 7,
    title: "عسل زهور الربيع + لانش بوكس",
    Image: "../../public/honey images/عسل زهور الربيع + لانش بوكس.jpg",
    price: "164.50ج.م",
  },
  {
    id: 8,
    title: "عسل بالمكسرات500جم",
    Image: "../../public/honey images/عسل بالمكسرات ٥٠٠ جم.jpg",
    price: "160ج.م",
  },
  {
    id: 10,
    title: "شمع بالعسل",
    Image: "../../public/honey images/شمع بالعسل.jpg",
    price: "140ج.م",
  },
  {
    id: 12,
    title: "عسل زهور الربيع",
    Image: "../../public/honey images/عسل زهور الربيع.jpg",
    price: "671ج.م",
  },
  {
    id: 13,
    title: "عسل سعودي(سدر جبلي)",
    Image: "../../public/honey images/عسل سعودي (سدر جبلي).jpg",
    price: "1000ج.م",
  },
  {
    id: 14,
    title: "عسل بردقوش",
    Image: "../../public/honey images/عسل بردقوش.jpg",
    price: "95ج.م",
  },
  {
    id: 15,
    title: "عسل دوعني",
    Image: "../../public/honey images/عسل دوعني.jpg",
    price: "1200ج.م",
  },
  {
    id: 16,
    title: "عسل كريمي بغزاءالملكات",
    Image: "../../public/honey images/عسل كريمي بغذاء الملكات.jpg",
    price: "1600ج.م",
  },
  {
    id: 17,
    title: "عسل حضرمي",
    Image: "../../public/honey images/عسل حضرمي.jpg",
    price: "1150ج.م",
  },
  {
    id: 18,
    title: "عسل زهور الربيع + البردقوش",
    Image: "../../public/honey images/عسل زهور الربيع + البردقوش.jpg",
    price: "164.50ج.م",
  },
  {
    id: 19,
    title: "عسل زهور الربيع + حبةالبركه",
    Image: "../../public/honey images/عسل زهور الربيع + حبة البركة.jpg",
    price: "164.50ج.م",
  },
  {
    id: 20,
    title: "عسل البرسيم + حبةالبركه",
    Image: "../../public/honey images/عسل البرسيم + حبة البركة.jpg",
    price: "164.50ج.م",
  },
  {
    id: 21,
    title: "عسل الجنكة",
    Image: "../../public/honey images/عسل الجنكة.jpg",
    price: "73ج.م",
  },
  {
    id: 22,
    title: "عسل زهرة الشوك",
    Image: "../../public/honey images/عسل زهور برية.jpg",
    price: "81ج.م",
  },
  {
    id: 23,
    title: "عسل حبة البركه",
    Image: "../../public/honey images/عسل حبة البركه.jpg",
    price: "74.50ج.م",
  },
  {
    id: 24,
    title: "عسل بعين الجمل",
    Image: "../../public/honey images/عسل بعين الجمل.png",
    price: "155ج.م",
  },
  {
    id: 25,
    title: "عسل فستق ايراني",
    Image: "../../public/honey images/عسل فستق ايراني.jpg",
    price: "228ج.م",
  },
  {
    id: 26,
    title: "شمع عسل",
    Image: "../../public/honey images/شمع عسل.jpg",
    price: "273.50ج.م",
  },
  {
    id: 27,
    title: "عسل بالمكسرات",
    Image: "../../public/honey images/عسل بالمكسرات ٥٠٠ جم.jpg",
    price: "271ج.م",
  },
  {
    id: 28,
    title: "عسل الاخناسيا",
    Image: "../../public/honey images/عسل الاخناسيا.jpg",
    price: "90ج.م",
  },
  {
    id: 29,
    title: "عسل البردقوش",
    Image: "../../public/honey images/عسل البردقوش.jpg",
    price: "108ج.م",
  },
  {
    id: 30,
    title: "عسل زهور برية",
    Image: "../../public/honey images/عسل زهور برية.jpg",
    price: "289ج.م",
  },
  {
    id: 31,
    title: "عسل النباتات الطبيه",
    Image: "../../public/honey images/عسل النباتات الطبية.jpg",
    price: "98.50ج.م",
  },
  {
    id: 32,
    title: "عسل زهور اسبانيا",
    Image: "../../public/honey images/عسل زهور أسبانيا.jpg",
    price: "207.50ج.م",
  },
  {
    id: 33,
    title: "عسل زهور الموالح",
    Image: "../../public/honey images/عسل زهور الموالح.jpg",
    price: "73ج.م",
  },
  {
    id: 34,
    title: "عسل حبة البركه",
    Image: "../../public/honey images/عسل حبة البركه.jpg",
    price: "73ج.م",
  },
  {
    id: 35,
    title: "عسل زهور الجنوب",
    Image: "../../public/honey images/عسل زهورالجنوب.jpg",
    price: "164.50ج.م",
  },
  {
    id: 36,
    title: "عسل خبز النحل ",
    Image: "../../public/honey images/عسل خبز النحل.jpg",
    price: "122ج.م",
  },
  {
    id: 37,
    title: "عسل بي اميون",
    Image: "../../public/honey images/عسل بي اميون.jpg",
    price: "235ج.م",
  },
  {
    id: 38,
    title: "عسل البرسيم",
    Image: "../../public/honey images/عسل زهور الربيع + لانش بوكس.jpg",
    price: "787ج.م",
  },
  {
    id: 39,
    title: "عسل سوبر اميون بالفانيليا",
    Image: "../../public/honey images/عسل سوبر اميون بالفانيليا.jpg",
    price: "149ج.م",
  },
  {
    id: 40,
    title: "عسل سوبر اميون بالشيكولاتة",
    Image: "../../public/honey images/عسل سوبر اميون بالشيكولاتة.jpg",
    price: "149ج.م",
  },
  {
    id: 41,
    title: "عسل الجينسينج",
    Image: "../../public/honey images/عسل الجينسينج.jpg",
    price: "217ج.م",
  },
  {
    id: 42,
    title: "عسل سدر جبلي مصري",
    Image: "../../public/honey images/عسل سدر جبلي مصري.jpg",
    price: "1288ج.م",
  },
  {
    id: 43,
    title: "عسل سدر جبلي كشميري",
    Image: "../../public/honey images/عسل سدر جبلي كشميري.jpg",
    price: "2685ج.م",
  },
  {
    id: 44,
    title: "عسل سدر جبلي خضرمي",
    Image: "../../public/honey images/عسل سدر جبلي خضرمي.jpg",
    price: "3860ج.م",
  },
];

export const herbalData = [
  {
    id: 1,
    title: "ورق سدر مجفف ٥۰ جم",
    Image: "../../public/herbal images/sider.png",
    price: "15ج.م",
  },
  {
    id: 2,
    title: "ورق الاس ۹۰ جم",
    Image: "../../public/herbal images/ass-paperpng.png",
    price: "15ج.م",
  },
  {
    id: 3,
    title: "عرعر مجفف ۹۰ جم",
    Image: "../../public/herbal images/arar.jpg",
    price: "15ج.م",
  },
  {
    id: 4,
    title: "مجلب النفاس ۱ كيلو ",
    Image: "../../public/herbal images/mglb-nfas.jpg",
    price: "15ج.م",
  },
  {
    id: 5,
    title: "حبق مجفف ٥۰ جم ",
    Image: "../../public/herbal images/hobok.jpg",
    price: "15ج.م",
  },
  {
    id: 6,
    title: "    ورق الجوافه ۸۰",
    Image: "../../public/herbal images/gawafa.png",
    price: "15ج.م",
  },
  {
    id: 7,
    title: "اكليل الجبل ( رزوماري ) ۱۲٥ جم",
    Image: "../../public/herbal images/iklil-algabal.jpg",
    price: "15ج.م",
  },
  {
    id: 8,
    title: "اسبيغول ۲۰۰ جم ",
    Image: "../../public/herbal images/isbeghol.png",
    price: "15ج.م",
  },
  {
    id: 9,
    title: "ورق محمدي ٥۰ جم  ",
    Image: "../../public/herbal images/mohamedy-paper.png",
    price: "15ج.م",
  },
  {
    id: 10,
    title: "ورق النيم",
    Image: "../../public/herbal images/neem-paper.png",
    price: "15ج.م",
  },
  {
    id: 11,
    title: "ورق زعتر  ",
    Image: "../../public/herbal images/zater-paper.jpg",
    price: "15ج.م",
  },
  {
    id: 12,
    title: " شيكاكاي ۱۲۰ جم ",
    Image: "../../public/herbal images/shikaki.jpg",
    price: "15ج.م",
  },
  {
    id: 13,
    title: " ميرمية ",
    Image: "../../public/herbal images/mirmia.jpg",
    price: "15ج.م",
  },
  {
    id: 14,
    title: " زعفران أبو شيبه فاخر ۲ جم ",
    Image: "../../public/herbal images/zafran-shiba.png",
    price: "15ج.م",
  },
  {
    id: 15,
    title: "  ورق وسمه ۱٥۰ جم  ",
    Image: "../../public/herbal images/wasma-paper.jpg",
    price: "15ج.م",
  },
  {
    id: 16,
    title: "القسط الهندي ۱۲٥ جم ",
    Image: "../../public/herbal images/indian-kist.png",
    price: "15ج.م",
  },
  {
    id: 17,
    title: "  قرفه سبلاني ۱٥۰ جم ",
    Image: "../../public/herbal images/krfa.png",
    price: "15ج.م",
  },
  {
    id: 18,
    title: " قرنفل ۲٥۰ جم    ",
    Image: "../../public/herbal images/kronfeljpg.jpg",
    price: "15ج.م",
  },
  {
    id: 19,
    title: "  خزامى / لافندر ٦۰ جم    ",
    Image: "../../public/herbal images/lavander.png",
    price: "15ج.م",
  },
  {
    id: 20,
    title: " بابونج ۱۲۰ جم ",
    Image: "../../public/herbal images/babongjpg.jpg",
    price: "15ج.م",
  },
  {
    id: 21,
    title: " مورينجا ۷٥ جم     ",
    Image: "../../public/herbal images/moringa.jpg",
    price: "15ج.م",
  },
  {
    id: 22,
    title: "   وسمه ( ناعم ) ۱۲٥ جم ",
    Image: "../../public/herbal images/smoth-wasma.png",
    price: "15ج.م",
  },
  {
    id: 23,
    title: "  ورق سنا ( سنامكي )  ",
    Image: "../../public/herbal images/sanamaki-paper.png",
    price: "15ج.م",
  },
];
